.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oxiarc-man 1  "oxiarc-man " 
.SH NAME
oxiarc\-man \- Generate man pages for all subcommands
.SH SYNOPSIS
\fBoxiarc\-man\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIOUT_DIR\fR] 
.SH DESCRIPTION
Generate man pages for all subcommands
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIOUT_DIR\fR]
Directory to write man pages into (default: ./man)
