.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oxiarc-info 1  "oxiarc-info " 
.SH NAME
oxiarc\-info \- Show information about an archive
.SH SYNOPSIS
\fBoxiarc\-info\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIARCHIVE\fR> 
.SH DESCRIPTION
Show information about an archive
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIARCHIVE\fR>
Archive file to inspect
