.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oxiarc-detect 1  "oxiarc-detect " 
.SH NAME
oxiarc\-detect \- Detect archive format
.SH SYNOPSIS
\fBoxiarc\-detect\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> 
.SH DESCRIPTION
Detect archive format
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFILE\fR>
File to detect
